version: '3'

services:

  # evans:
  #   image: evans-test
  #   build:
  #     context: .
  #     dockerfile: evans.dockerfile    
  #   container_name: evans
  #   volumes:      
  #     - ./proto/:/proto:ro    
  #   ports:
  #     - '50051:50051'
  #   command: | 
  #     -s
    #  "--path ./proto \
    #   --proto auth_service.proto \
    #   --host  tcp://vacancies.cyrextech.net:7823 \
    #   --port 50051 \
    #   repl"

  master:
    image: locustio/locust
    container_name: locust_master
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile_client.py --master -H http://master:8089
  
  worker:
    image: my_locust
    build:
      context: .
      dockerfile: locust.dockerfile    
    container_name: locust_client
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile_client.py  --master-host master
      
